name: 'Build'
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
